name: publish
on: push

jobs:
  build_and_publish:
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-20.04]
            os-is-always-linux: [linux]
            architecture: [x64]
            # note on aarch64: https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/
            # tl;dr available to paying github users but not available yet to open source
    runs-on: ["${{ matrix.os }}"]  # "${{ matrix.architecture }}"

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Log in to the Container registry
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

    # - name: Check tag matches package version
    #   run:  |
    #     package_ver=$(./zcripts --version | grep -Eo 'v\S+$')
    #     if ! [[ $package_ver == $GITHUB_REF_NAME ]]; then
    #       echo "Refusing to release because tag doesn't match --version: $GITHUB_REF_NAME != $package_ver" 1>&2
    #       echo "(You probably need to update pyproject.toml)" 1>&2
    #       exit 1
    #     fi
    #   if: startsWith(github.ref, 'refs/tags/')
    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: |
    #       ./zcripts_${{ matrix.os-is-always-linux }}_${{ matrix.architecture }}
    #       ./install-zcripts_${{ matrix.architecture }}.run
    #       bin/install-zcripts.sh
