name: publish
on: push

jobs:
  build_and_publish:
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-20.04]
            os-is-always-linux: [linux]
            architecture: [x64]
            # note on aarch64: https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/
            # tl;dr available to paying github users but not available yet to open source
    runs-on: ["${{ matrix.os }}"]  # "${{ matrix.architecture }}"

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ github.token }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: cronan
          tags: v1 ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          build-args: |
            ORG_OPENCONTAINERS_IMAGE_SOURCE=https://ghcr.io/corydodt/cronan
            ORG_OPENCONTAINERS_IMAGE_DESCRIPTION=cronan smash

      - name: Push to ghcr
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/corydodt
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
