name: publish
on: push

jobs:
  build_and_publish:
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-24.04]
            os-is-always-linux: [linux]
            architecture: [x64]
            # note on aarch64: https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/
            # tl;dr available to paying github users but not available yet to open source
    runs-on: ["${{ matrix.os }}"]  # "${{ matrix.architecture }}"

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ github.token }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: make image

      - name: Push to ghcr
        run: |
          echo $REGISTRY_PASSWORD | make login
          make push
          echo $REGISTRY_PASSWORD | make print-url
